all:
	clang++ -Wall -Wextra -Werror ClapTrap.cpp ClapTrap.hpp main.cpp

clean:
	rm -rf a.out ClapTrap.hpp.gch

re:
	rm -rf a.out ClapTrap.hpp.gch
	lang++ -Wall -Wextra -Werror ClapTrap.cpp ClapTrap.hpp main.cpp