all:
	clang++ -std=c++98 -Wall -Wextra -Werror Bureaucrat.hpp Bureaucrat.cpp Form.cpp Form.hpp ShrubberyCreationForm.cpp ShrubberyCreationForm.hpp RobotomyRequestForm.cpp RobotomyRequestForm.hpp PresidentialPardonForm.cpp PresidentialPardonForm.hpp Intern.hpp Intern.cpp main.cpp

clean:
	rm -rf a.out Bureaucrat.hpp.gch Form.hpp.gch ShrubberyCreationForm.hpp.gch RobotomyRequestForm.hpp.gch PresidentialPardonForm.hpp.gch Intern.hpp.gch

re:
	rm -rf a.out Bureaucrat.hpp.gch Form.hpp.gch
	clang++ -std=c++98 -Wall -Wextra -Werror Bureaucrat.hpp Bureaucrat.cpp Form.cpp Form.hpp ShrubberyCreationForm.cpp ShrubberyCreationForm.hpp RobotomyRequestForm.cpp RobotomyRequestForm.hpp PresidentialPardonForm.cpp PresidentialPardonForm.hpp Intern.hpp Intern.cpp main.cpp