all:
	clang++ -Wall -Wextra -Werror main.cpp Zombie.cpp Zombie.hpp ZombieHorde.hpp ZombieHorde.cpp

clean:
	rm -rf a.out Zombie.hpp.gch ZombieHorde.hpp.gch

re:
	rm -rf a.out Zombie.hpp.gch ZombieHorde.hpp.gch
	clang++ -Wall -Wextra -Werror main.cpp Zombie.cpp Zombie.hpp ZombieHorde.hpp ZombieHorde.cpp
