all:
	clang++ -Wall -Wextra -Werror AWeapon.cpp Character.cpp Enemy.cpp PlasmaRifle.hpp PowerFist.hpp RadScorpion.hpp SuperMutant.hpp AWeapon.hpp Character.hpp Enemy.hpp PlasmaRifle.cpp PowerFist.cpp RadScorpion.cpp SuperMutant.cpp OneMoreEnemy.cpp OneMoreEnemy.hpp main.cpp

clean:
	rm -rf a.out PlasmaRifle.hpp.gch PowerFist.hpp.gch RadScorpion.hpp.gch SuperMutant.hpp.gch Character.hpp.gch AWeapon.hpp.gch Enemy.hpp.gch OneMoreEnemy.hpp.gch

re:
	rm -rf a.out ClapTrap.hpp.gch ScavTrap.hpp.gch
	clang++ -Wall -Wextra -Werror AWeapon.cpp Character.cpp Enemy.cpp PlasmaRifle.hpp PowerFist.hpp RadScorpion.hpp SuperMutant.hpp AWeapon.hpp Character.hpp Enemy.hpp PlasmaRifle.cpp PowerFist.cpp RadScorpion.cpp SuperMutant.cpp OneMoreEnemy.cpp OneMoreEnemy.hpp main.cpp