all:
	clang++ -Wall -Wextra -Werror main.cpp Zombie.cpp Zombie.hpp ZombieEvent.hpp ZombieEvent.cpp

clean:
	rm -rf a.out Zombie.hpp.gch ZombieEvent.hpp.gch

re:
	rm -rf a.out Zombie.hpp.gch ZombieEvent.hpp.gch
	clang++ -Wall -Wextra -Werror main.cpp Zombie.cpp Zombie.hpp ZombieEvent.hpp ZombieEvent.cpp
