all:
	clang++ -Wall -Wextra -Werror Brain.cpp Brain.hpp Human.cpp Human.hpp main.cpp

clean:
	rm -rf a.out Brain.hpp.gch Human.hpp.gch

re:
	rm -rf a.out Brain.hpp.gch Human.hpp.gch
	clang++ -Wall -Wextra -Werror Brain.cpp Brain.hpp Human.cpp Human.hpp main.cpp