all:
	clang++ -Wall -Wextra -Werror ClapTrap.cpp ClapTrap.hpp ScavTrap.cpp ScavTrap.hpp main.cpp

clean:
	rm -rf a.out ClapTrap.hpp.gch ScavTrap.hpp.gch

re:
	rm -rf a.out ClapTrap.hpp.gch ScavTrap.hpp.gch
	clang++ -Wall -Wextra -Werror ClapTrap.cpp ClapTrap.hpp ScavTrap.cpp ScavTrap.hpp main.cpp