all:
	clang++ -std=c++98 -Wall -Wextra -Werror AMateria.hpp AMateria.cpp Ice.hpp Ice.cpp Cure.hpp Cure.cpp Character.hpp Character.cpp MateriaSource.hpp MateriaSource.cpp ICharacter.hpp IMateriaSource.hpp main.cpp

clean:
	rm -rf a.out AMateria.hpp.gch Ice.hpp.gch Cure.hpp.gch Character.hpp.gch MateriaSource.hpp.gch IMateriaSource.hpp.gch ICharacter.hpp.gch

re:
	rm -rf a.out AMateria.hpp.gch Ice.hpp.gch Cure.hpp.gch Character.hpp.gch MateriaSource.hpp.gch IMateriaSource.hpp.gch ICharacter.hpp.gch
	clang++ -std=c++98 -Wall -Wextra -Werror AMateria.hpp AMateria.cpp Ice.hpp Ice.cpp Cure.hpp Cure.cpp Character.hpp Character.cpp MateriaSource.hpp MateriaSource.cpp ICharacter.hpp IMateriaSource.hpp main.cpp