all:
	clang++ -std=c++98 -Wall -Wextra -Werror Bureaucrat.hpp Bureaucrat.cpp main.cpp

clean:
	rm -rf a.out Bureaucrat.hpp.gch

re:
	rm -rf a.out Bureaucrat.hpp.gch
	clang++ -std=c++98 -Wall -Wextra -Werror Bureaucrat.hpp Bureaucrat.cpp main.cpp