all:
	clang++ -Wall -Wextra -Werror HumanA.cpp HumanA.hpp HumanB.cpp HumanB.hpp Weapon.cpp Weapon.hpp main.cpp

clean:
	rm -rf a.out HumanA.hpp.gch HumanB.hpp.gch Weapon.hpp.gch

re:
	rm -rf a.out HumanA.hpp.gch HumanB.hpp.gch Weapon.hpp.gch
	clang++ -Wall -Wextra -Werror HumanA.cpp HumanA.hpp HumanB.cpp HumanB.hpp Weapon.cpp Weapon.hpp main.cpp