all:
	clang++ -std=c++98 -Wall -Wextra -Werror AssaultTerminator.cpp ISpaceMarine.hpp Squad.cpp TacticalMarine.cpp main.cpp AssaultTerminator.hpp ISquad.hpp Squad.hpp TacticalMarine.hpp

clean:
	rm -rf a.out ISpaceMarine.hpp.gch AssaultTerminator.hpp.gch TacticalMarine.hpp.gch Squad.hpp.gch ISquad.hpp.gch Squad.hpp.gch

re:
	rm -rf a.out ISpaceMarine.hpp.gch AssaultTerminator.hpp.gch TacticalMarine.hpp.gch Squad.hpp.gch ISquad.hpp.gch Squad.hpp.gch
	clang++ -std=c++98 -Wall -Wextra -Werror AssaultTerminator.cpp ISpaceMarine.hpp Squad.cpp TacticalMarine.cpp main.cpp AssaultTerminator.hpp ISquad.hpp Squad.hpp TacticalMarine.hpp