all:
	clang++ -std=c++98 -Wall -Wextra -Werror main.cpp Base.hpp Base.cpp

clean:
	rm -rf a.out Base.hpp.gch

re:
	rm -rf a.out Base.hpp.gch
	clang++ -std=c++98 -Wall -Wextra -Werror main.cpp Base.hpp Base.cpp